{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-events-logger.fullname" . }}-view
  labels:
    {{- include "k8s-events-logger.labels" . | nindent 4 }}
rules:
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["*"]
- apiGroups: ["core.v1"]
  resources: ["events"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["*"]
{{- end -}}