apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-events-logger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: k8s-events-logger
  namespace: default
# ---
# kind: Role
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: k8s-events-logger-view
#   namespace: default
# rules:
# - apiGroups: ["events.k8s.io"]
#   resources: ["events"]
#   verbs: ["*"]
# - apiGroups: ["core.v1"]
#   resources: ["events"]
#   verbs: ["*"]
# - apiGroups: [""]
#   resources: ["events"]
#   verbs: ["*"]
# ---
# kind: RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: k8s-events-logger
#   namespace: default
# roleRef:
#   kind: Role
#   name: k8s-events-logger-view
#   apiGroup: rbac.authorization.k8s.io
# subjects:
# - kind: ServiceAccount
#   name: k8s-events-logger
#   namespace: default